LMS/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LMS.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }

    }
}

LMS/Controllers/UserProfileController.cs
using LMS.Models.UserProfile;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LMS.Controllers
{
    public class UserProfileController : Controller
    {
        // GET: UserProfile
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Update(FormCollection form)
        {
            string UserID = System.Web.HttpContext.Current.Session["RecID"].ToString();
            string password = Request.Form["password"].ToString();
            string phone = Request.Form["phone"].ToString();
            string address = Request.Form["address"].ToString();
            string submit = UserProfile.UserUpdate(address,phone,password,UserID);
            return RedirectToAction("Index");
        }

    }
}

LMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LMS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/all.min.css" rel="stylesheet" />
    <link href="~/Content/fontawesome.min.css" rel="stylesheet" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />

    <style>
        .text-white {
            color: white;
        }

        body {
            font-family: "Lato", sans-serif;
        }

        .sidenav {
            height: 95%;
            width: 15%;
            position: fixed;
            z-index: 1;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 20px;
        }

            .sidenav a {
                padding: 6px 6px 6px 32px;
                text-decoration: none;
                font-size: 25px;
                color: #818181;
                display: block;
            }

                .sidenav a:hover {
                    background-color: #f1f1f18c;
                    color: #111111;
                }
    </style>
</head>
<body>

    <div class="navbar navbar-fixed-top text-white" style="background-color:#399039;">
        <div class="row">
            <div class="col-md-3" style="text-align:center; ">
                <div class="navbar-header">

                    @Html.ActionLink("Mobilelink USA", "Index", "dashboard", new { area = "" }, new { @class = "navbar-brand text-white text-center", @style = "text-align:center; " })
                </div>
            </div>
            <div class="col-md-9">

                <div class="dropdown" style="float:right;">
                    <div class="btn  text-white text-center navbar-brand dropdown-toggle" style="margin-right:70px;" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div style="float:right;">
                            <i class="fas fa-user"></i> Porfile
                        </div>
                    </div>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <br />
                        <a class="dropdown-item" href="@Url.Action("Index","UserProfile")">Action</a>
                        <br />
                        <a class="dropdown-item" href="#">Preferences</a>
                        <br />
                        <a class="dropdown-item" href="@Url.Action("LogOut","Home" , new { id=1 })">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                        <br />
                    </div>
                </div>

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>


        </div>

    </div>

    <div class="row">
        <div class="sidenav col-md-2">
            <a href="" style="background-color:none;">@Session["Name"]</a>
            <a href="@Url.Action("index","dashboard")"><i class="fas fa-tachometer-alt"></i> Dashboard</a>
            <a href="@Url.Action("index","News")"><i class="fas fa-pen-alt"></i> News</a>
        </div>


        <div class="col-md-9 col-sm-12 col-xs-12 body-content" style="margin-left:17%;">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - All Rights Reserved by <a href="#">Mobilelink USA</a></p>
            </footer>
        </div>
    </div>





    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <script src="~/Scripts/jquery-3.3.1.min.js"></script>

</body>

</html>

LMS/Views/Shared/accessdenied.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Access Denied</title>
    <link rel="icon" href="~/Image/favicon.png" type="image/gif" sizes="16x16">
</head>
<body onload="altit()" style="background:#eee;font-family: 'Open Sans', sans-serif;" >
    <script>
        function altit() {
            swal({
                title: "Access Denied!",
                text: "WEB Department",
                icon: "warning",
                buttons: "Close",
                closeOnClickOutside: false,
                closeOnEsc: false,
            });
            setTimeout(function () {
                @*window.location = "@System.Configuration.ConfigurationManager.AppSettings["home"]";*@
                window.location ="@System.Configuration.ConfigurationManager.AppSettings["home"]";
            }, 1500);
        }
    </script>
</body>
</html>

LMS/Views/Shared/loginfailed.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Login Failed</title>
    <link rel="icon" href="~/Image/favicon.png" type="image/gif" sizes="16x16">
</head>
<body onload="altit()" style="background:#eee;font-family: 'Open Sans', sans-serif;">
    <script>
            swal({
                title: "Login Failed!",
                text: "Web Department",
                icon: "warning",
                buttons: "Close",
                closeOnClickOutside: false,
                closeOnEsc: false,
            });
            setTimeout(function () {
                window.location = "@System.Configuration.ConfigurationManager.AppSettings["loginfailed"]";
            }, 1500);
        
    </script>
</body>
</html>

LMS/Views/Shared/sessionexpire.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <meta name="viewport" content="width=device-width" />
    <title>Access Denied</title>
    <link rel="icon" href="~/Image/favicon.png" type="image/gif" sizes="16x16">
</head>
<body onload="altit()" style="background:#eee;font-family: 'Open Sans', sans-serif;">
    <script>
        function altit() {
            swal({
                title: "Session Expired!",
                text: "Web Department",
                icon: "warning",
                buttons: "Close",
                closeOnClickOutside: false,
                closeOnEsc: false,
            });
            setTimeout(function () {
                window.location = "@System.Configuration.ConfigurationManager.AppSettings["loginfailed"]";
            }, 2500);
        }
    </script>
</body>
</html>