LMS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LMS.Models.Loginuser;

namespace LMS.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            if (Session["RecID"] != null)
            {
                string UserID = System.Web.HttpContext.Current.Session["RecID"].ToString();
                DataTable dt = Loginvalid.usermenu(UserID);
                List<Usermenu> menus = new List<Usermenu>();
                foreach (DataRow dc in dt.Rows)
                {
                    Usermenu menu = new Usermenu();
                    menu.MenuIteam = dc["MenuIteam"].ToString();
                    menu.Icon = dc["Icon"].ToString();
                    menu.Class = dc["Class"].ToString();
                    menu.URL = dc["URL"].ToString();

                    menus.Add(menu);
                }

                ViewData["MenuDetails"] = menus;
                return View();
            }
            else
            {
                return View("SessionExpire");
            }
        }
    }
}

LMS/Controllers/PrivateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LMS.Controllers
{
    public class PrivateController : Controller
    {
        // GET: Private
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddFile()
        {
            return View();
        }
    }
}

LMS/Views/Private/AddFile.cshtml
@{
    ViewBag.Title = "AddFile";
}

<div class="LMS_Header">@ViewBag.Title</div>
<div class="LMS_body">
<form class="form">

    <div class="form-group">
        <label class="newbtn btn">
            <img id="blah" src="https://www.itnamerica.org/assets/images/file-upload-icon.png">
            <input id="pic" class='pis hidden' onchange="readURL(this);" type="file">
        <code>Select one Video Lecture at a time.</code>
        </label>
    </div>

    <br />
    <div class="form-group">
        <input type="submit" name="submit" value="Add Private File" class="btn btn-success" />
        <a href="@Url.Action("Index","Private")" value="" class="btn btn-primary" style="margin-left:54%;">Previously Uploaded Files</a>
    </div>

</form>
</div>

LMS/Views/Private/Index.cshtml
@{
    ViewBag.Title = "Private Files";
}

<div class="LMS_Header">
    <div class="row">
        <div class="col-md-6 col-md-6 col-sm-12 col-xs-12">
            <a href="@Url.Action("Index","Dashboard")" class="btn"><i class="fas fa-backward"></i> Back</a>
            @ViewBag.Title
        </div>
        <a href="@Url.Action("AddFile","Private")" class="col-md-4 col-md-4 col-sm-12 col-xs-12 btn btn-primary" style="margin-left:15%;">Add File</a>
    </div>
</div>
<div class="LMS_body">
    <div class="row">
        <div class="col-md-10 col-lg-10 col-sm-12 col-xs-12">
            <a href="https://sweetalert.js.org/assets/images/logo.svg" download><h3>Alforda Brazilia</h3></a>
        </div>
        <div class="col-md-2 col-lg-2 col-sm-12 col-xs-12" style="margin-top:1%;">
            <input type="button" class="btn btn-danger" value="Delete" name="Delete" id="btndelete" />
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">
                $(document).ready(function ()
                {
                    $("#btndelete").click(function () {
                        swal({
                            title: "Are you sure?",
                            text: "Once deleted, you will not be able to recover this Private File!",
                            icon: "warning",
                            buttons: true,
                            dangerMode: true,
                        })
.then((willDelete) => {
    if (willDelete) {
        swal("Poof! Your Document has been deleted!", {
            icon: "success",
        });

    } else {
        swal("Your Document file is safe!");
    }
});
                    });
                    });
</script>