LMS/Controllers/ClassroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LMS.Controllers
{
    public class ClassroomController : Controller
    {
        // GET: Classroom
        public ActionResult Index()
        {
            return View();
        }

        // GET: Recording
        public ActionResult Recording()
        {
            return View();
        }

        // GET: RecordingList
        public ActionResult LecturesList()
        {
            return View();
        }

        public ActionResult Delete()
        {
            ViewBag.response = 1;
            return RedirectToAction("LecturesList");
        }

        public ActionResult Edit()
        {
            return View();
        }

        public ActionResult Classroom()
        {
            return View();
        }
    }
}

LMS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LMS.Models.Loginuser;

namespace LMS.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            if (Session["RecID"] != null)
            {
                string UserID = System.Web.HttpContext.Current.Session["RecID"].ToString();
                DataTable dt = Loginvalid.usermenu(UserID);
                List<Usermenu> menus = new List<Usermenu>();
                foreach (DataRow dc in dt.Rows)
                {
                    Usermenu menu = new Usermenu();
                    menu.MenuIteam = dc["MenuIteam"].ToString();
                    menu.Icon = dc["Icon"].ToString();
                    menu.Class = dc["Class"].ToString();
                    menu.URL = dc["URL"].ToString();

                    menus.Add(menu);
                }

                ViewData["MenuDetails"] = menus;
                return View();
            }
            else
            {
                return View("SessionExpire");
            }
        }
    }
}

LMS/Views/Classroom/Classroom.cshtml
@{ 
    ViewBag.Title = "ClassRoom";
}
<div class="LMS_Header">
    <a href="@Url.Action("LecturesList","Classroom")" class="btn"><i class="fas fa-backward"></i> Back</a>
    How to Install Noodle
</div>
<div class="LMS_body">
    
    <div class="form-group">
        <iframe width="560" style="height:400pt!important;" src="https://www.youtube.com/embed/np7BPMRgTeQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" class="form-control" allowfullscreen></iframe>
    </div>
    <div class="form-group">
        <h5><strong>Description:</strong>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</h5>
        <h5><strong>Attachments:</strong> <a href="/uploads/media/default/0001/01/540cb75550adf33f281f29132dddd14fded85bfc.pdf">PDF 1</a>,<a href="/uploads/media/default/0001/01/540cb75550adf33f281f29132dddd14fded85bfc.pdf">PDF 2</a></h5>
    </div>

    @*Comments*@
    <hr />
    <form action="#" method="post" class="form">

        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading" id="accordion">
                            <span class="glyphicon glyphicon-comment"></span> Discussion Box
                            <div class="btn-group pull-right">
                                <a type="button" class="btn btn-default btn-xs" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                    <span class="glyphicon glyphicon-chevron-down"></span>
                                </a>
                            </div>
                        </div>
                        <div class="panel-collapse collapse" id="collapseOne">
                            <div class="panel-body">
                                <ul class="chat">
                                    <li class="left clearfix">
                                        <span class="chat-img pull-left">
                                            <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
                                        </span>
                                        <div class="chat-body clearfix">
                                            <div class="header">
                                                <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                                    <span class="glyphicon glyphicon-time"></span>12 mins ago
                                                </small>
                                            </div>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                                dolor, quis ullamcorper ligula sodales.
                                            </p>
                                        </div>
                                    </li>
                                    <li class="right clearfix">
                                        <span class="chat-img pull-right">
                                            <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
                                        </span>
                                        <div class="chat-body clearfix">
                                            <div class="header">
                                                <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>13 mins ago</small>
                                                <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                            </div>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                                dolor, quis ullamcorper ligula sodales.
                                            </p>
                                        </div>
                                    </li>
                                    <li class="left clearfix">
                                        <span class="chat-img pull-left">
                                            <img src="http://placehold.it/50/55C1E7/fff&text=U" alt="User Avatar" class="img-circle" />
                                        </span>
                                        <div class="chat-body clearfix">
                                            <div class="header">
                                                <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                                    <span class="glyphicon glyphicon-time"></span>14 mins ago
                                                </small>
                                            </div>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                                dolor, quis ullamcorper ligula sodales.
                                            </p>
                                        </div>
                                    </li>
                                    <li class="right clearfix">
                                        <span class="chat-img pull-right">
                                            <img src="http://placehold.it/50/FA6F57/fff&text=ME" alt="User Avatar" class="img-circle" />
                                        </span>
                                        <div class="chat-body clearfix">
                                            <div class="header">
                                                <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>15 mins ago</small>
                                                <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                            </div>
                                            <p>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                                dolor, quis ullamcorper ligula sodales.
                                            </p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="panel-footer">
                                <div class="input-group">
                                    <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here..." />
                                    <span class="input-group-btn">
                                        <button class="btn btn-warning btn-sm" id="btn-chat">
                                            Send
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </form>

</div>
<style>
    .chat
{
    list-style: none;
    margin: 0;
    padding: 0;
}

.chat li
{
    margin-bottom: 10px;
    padding-bottom: 5px;
    border-bottom: 1px dotted #B3A9A9;
}

.chat li.left .chat-body
{
    margin-left: 60px;
}

.chat li.right .chat-body
{
    margin-right: 60px;
}


.chat li .chat-body p
{
    margin: 0;
    color: #777777;
}

.panel .slidedown .glyphicon, .chat .glyphicon
{
    margin-right: 5px;
}

.panel-body
{
    overflow-y: scroll;
    height: 250px;
}

::-webkit-scrollbar-track
{
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    background-color: #F5F5F5;
}

::-webkit-scrollbar
{
    width: 12px;
    background-color: #F5F5F5;
}

::-webkit-scrollbar-thumb
{
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
    background-color: #555;
}

</style>

LMS/Views/Classroom/Edit.cshtml
@{ 
    ViewBag.Title = "Edit Lecture";
}
<style>
    .max-width{
        max-width:initial;
    }
</style>
<div class="LMS_Header">
    @ViewBag.Title
</div>
<div class="LMS_body">
    <form method="post" action="@Url.Action("LecturesList","Classroom")" class="form">

        <div class="form-group">
            <label class="control-label">Title:</label>
            <input type="text" class="form-control max-width" placeholder="Enter Title"/>
        </div>

        <div class="form-group">
            <label class="control-label">Description:</label>
            <input type="text" class="form-control max-width" placeholder="Enter Description" />
        </div>

        <div class="form-group">
            <label class="control-label">Previous Lecture preview:</label>
            <iframe width="560" style="height:400pt!important;" src="https://www.youtube.com/embed/v8A8qmsas08" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" class="form-control" allowfullscreen></iframe>
        </div>

        <div class="form-group" style="margin-left:27%;">
            <label class="control-label">Upload New Lecture</label>
            <label class="newbtn btn">
                <img id="blah" src="https://www.itnamerica.org/assets/images/file-upload-icon.png">
                <input id="pic" class='pis hidden' onchange="readURL(this);" type="file">
                <code>Select One Lecture at a time!</code>
            </label>
        </div>

        <div class="form-group">
            <a href="@Url.Action("LecturesList","Classroom")" class="btn btn-warning form-control">Cancel</a>
            <br />
            <br />
            <input type="submit" class="btn btn-success form-control max-width" value="Update Record"/>
        </div>


    </form>
</div>

LMS/Views/Classroom/Index.cshtml
@{
    ViewBag.Title = "Class Room";
}
<div class="LMS_Header">
    <a href="@Url.Action("Index","Dashboard")" class="btn"><i class="fas fa-backward"></i> Back</a>

    <i class="fas fa-chalkboard-teacher"></i> @ViewBag.Title
</div>
<div class="LMS_body">
    <div class="row">
        <div class="quiz-table col-md-3" style="">
            <img src="~/images/system.png" style="padding: 10px; border-radius: 10px; margin-top: 20px; width:40%;">
            <hr style="height:2px;" />
            <h2>English</h2>
            <a href="@Url.Action("LecturesList","classroom" , new { id = 123 })" value="123" class="btn btn-danger"><i class="fas fa-video"></i> Lectures</a>
        </div>
    </div>
</div>

LMS/Views/Classroom/LecturesList.cshtml
@{
    ViewBag.Title = "Uploaded Lectures";
}

<div class="LMS_Header">
    

    
    <div class="row">
        <div class="col-md-6 col-md-6 col-sm-12 col-xs-12">
            <a href="@Url.Action("Index","Classroom")" class="btn"><i class="fas fa-backward"></i> Back</a>
            <i class="fas fa-chalkboard-teacher"></i> @ViewBag.Title
        </div>
        <a href="@Url.Action("Recording","Classroom")" class="col-md-4 col-md-4 col-sm-12 col-xs-12 btn btn-primary" style="margin-left:15%; color:white!important;">Add New Lecture</a>
    </div>
</div>
<div class="LMS_body">
    <div class="row">
        <div class="col-md-10 col-lg-10 col-sm-12 col-xs-12">
            <a href="@Url.Action("Classroom","Classroom")"><h3>1) How to Install Noodle</h3></a>
        </div>
        <div class="col-md-2 col-lg-2 col-sm-12 col-xs-12" style="margin-top:1%;">
            <a class="btn btn-warning" href="@Url.Action("Edit","Classroom")">Edit</a>
            <input type="button" class="btn btn-danger" value="Delete" name="Delete" id="btndelete" />
        </div>
    </div>
    <hr style="width:95%; padding:0; border: 1px solid green;"/>
    <div class="row">
        <div class="col-md-10 col-lg-10 col-sm-12 col-xs-12">
            <a href="@Url.Action("Classroom","Classroom")"><h3>2) How to Install Noodle</h3></a>

        </div>
        <div class="col-md-2 col-lg-2 col-sm-12 col-xs-12" style="margin-top:1%;">
            <a class="btn btn-warning" href="@Url.Action("Edit","Classroom")">Edit</a>
            <input type="button" class="btn btn-danger" value="Delete" name="Delete" id="btndelete" />
        </div>
    </div>
    <hr style="width:95%; padding:0; border: 1px solid green;" />
    <div class="row">
        <div class="col-md-10 col-lg-10 col-sm-12 col-xs-12">
            <a href="@Url.Action("Classroom","Classroom")"><h3>3) How to Install Noodle</h3></a>

        </div>
        <div class="col-md-2 col-lg-2 col-sm-12 col-xs-12" style="margin-top:1%;">
            <a class="btn btn-warning" href="@Url.Action("Edit","Classroom")">Edit</a>
            <input type="button" class="btn btn-danger" value="Delete" name="Delete" id="btndelete" />
        </div>
    </div>
    <hr style="width:95%; padding:0; border: 1px solid green;" />
    
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
            <script type="text/javascript">
                $(document).ready(function ()
                {
                    $("#btndelete").click(function () {
                        swal({
                            title: "Are you sure?",
                            text: "Once deleted, you will not be able to recover this imaginary file!",
                            icon: "warning",
                            buttons: true,
                            dangerMode: true,
                        })
.then((willDelete) => {
    if (willDelete) {
        swal("Poof! Your Lecture & file has been deleted!", {
            icon: "success",
        });

    } else {
        swal("Your Lecture file is safe!");
    }
});
                    });
                    });
            </script>
            

LMS/Views/Classroom/Recording.cshtml
@{
    ViewBag.Title = "Add New Lecture";
}
<div class="LMS_Header">English Class</div>
<div class="LMS_body">
    <form class="form" action="#" method="post">


        <div class="row">

            <div class="form-group col-md-12 col-lg-12">
                <label class="control-label col-md-12">Title: </label>
                <input id="" type="text" class="form-control" name="name" value="" style="max-width:100%;" />
            </div>

            <div class="form-group col-md-12 col-lg-12">
                <label class="control-label col-md-12">Description: </label>
                <textarea type="text" class="form-control " name="name" value="Enter Description" style="max-width:100%; height:200px;" /></textarea>
            </div>

            <div class="form-group">
                <label class="newbtn btn">
                    <img id="blah" src="https://www.itnamerica.org/assets/images/file-upload-icon.png">
                    <input id="pic" class='pis hidden' onchange="readURL(this);" type="file">
                </label>
            </div>
            <div class="form-group">
                <code>Select one Video Lecture at a time.</code>
                <input type="submit" name="submit" value="Add New Lecture" class="btn btn-success" />
                <a href="@Url.Action("LecturesList","Classroom")" value="" class="btn btn-primary" style="margin-left:54%;" >Previously Uploaded Lectures</a>

            </div>
        </div>

    </form>
    <style>

        #xyz{
            width:100%;
        }

        #upload {
            display: none;
        }

        .newbtn {
            cursor: pointer;
        }

        #blah {
            float:right;
            border:1px dashed gray;
            border-radius:3px ;
            max-width: 200px;
            height: 200px;
            margin-top: 20px;
        }
    </style>
</div>