LMS/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LMS.Models.Loginuser;

namespace LMS.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            if (Session["RecID"] != null)
            {
                string UserID = System.Web.HttpContext.Current.Session["RecID"].ToString();
                DataTable dt = Loginvalid.usermenu(UserID);
                List<Usermenu> menus = new List<Usermenu>();
                foreach (DataRow dc in dt.Rows)
                {
                    Usermenu menu = new Usermenu();
                    menu.MenuIteam = dc["MenuIteam"].ToString();
                    menu.Icon = dc["Icon"].ToString();
                    menu.Class = dc["Class"].ToString();
                    menu.URL = dc["URL"].ToString();

                    menus.Add(menu);
                }

                ViewData["MenuDetails"] = menus;
                return View();
            }
            else
            {
                return View("SessionExpire");
            }
        }
    }
}

LMS/Controllers/FieldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LMS.Controllers
{
    public class FieldController : Controller
    {
        // GET: Field
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IT()
        {
            return View();
        }

        public ActionResult Student()
        {
            return View();
        }

        public ActionResult Instructors()
        {
            return View();
        }

        public ActionResult Recovery()
        {
            return View();
        }

        public ActionResult Users()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult UserUpdate()
        {
            return View();
        }

        public ActionResult NewUser()
        {
            return View();
        }

        public ActionResult RoleAssignment()
        {
            return View();
        }

        public ActionResult PermAssignment()
        {
            return View();
        }

        public ActionResult NewOrganization()
        {
            return View();
        }

        public ActionResult ManageOrganization()
        {
            return View();
        }

        public ActionResult UpdateOrganization()
        {
            return View();
        }

        public ActionResult WebNewUser()
        {
            return View();
        }

        public ActionResult WebUsers()
        {
            return View();
        }

        public ActionResult WebUpdateUser()
        {
            return View();
        }
    }
}

LMS/Views/Field/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

LMS/Views/Field/IT.cshtml
@{
    ViewBag.Title = "Team IT";
}

<style>
    .catlog {
        padding: 1%;
        margin-top: 1%;
        margin-left: 6%;
        font-size: 20px;
        padding-top: 2%;
        padding-bottom: 2%;
    }

    .Assessment {
        background-color: red;
    }
</style>

<div class="LMS_Header">
    <a href="@Url.Action("Index","Field")" class="btn"><i class="fas fa-backward"></i> Back</a>

    <i class="fas fa-fingerprint"></i> @ViewBag.Title
</div>

<div class="LMS_body col-sm-12 col-xs-12">

    <div class="row">

        <a class="col-md-5 catlog btn btn-success col-sm-10 col-xs-10" href="@Url.Action("RoleAssignment","Field")">
            <i class="fas fa-user-tag"></i> Role Assignment
        </a>

        <a class="col-md-5 catlog btn btn-danger col-sm-10 col-xs-10" href="@Url.Action("PermAssignment","Field")">
            <i class="fas fa-user-shield"></i> Permission Assignment
        </a>

    </div>
</div>

LMS/Views/Field/Index.cshtml
@{
    ViewBag.Title = "Fields";
}
<style>
    .catlog {
        padding: 1%;
        margin-top: 1%;
        margin-left: 6%;
        font-size: 20px;
        padding-top: 2%;
        padding-bottom: 2%;
    }

    .Assessment {
        background-color: red;
    }
</style>
<div class="LMS_Header">
    <a href="@Url.Action("Index","Dashboard")" class="btn"><i class="fas fa-backward"></i> Back</a>

    <i class="fas fa-swatchbook"></i> @ViewBag.Title
</div>
<div class="LMS_body col-sm-12 col-xs-12">

    <div class="row">

        <a class="col-md-5 catlog btn btn-danger col-sm-10 col-xs-10" href="@Url.Action("IT","Field")">
            <i class="fas fa-fingerprint"></i> IT
        </a>

        <a class="col-md-5 catlog btn btn-warning col-sm-10 col-xs-10" href="@Url.Action("Student","Field")">
            <i class="fas fa-user-graduate"></i> Student
        </a>

        <a class="col-md-5 catlog btn btn-primary col-sm-10 col-xs-10" href="@Url.Action("Instructors","Field")">
            <i class="fas fa-chalkboard-teacher"></i> Instructors
        </a>

        <a class="col-md-5 catlog btn btn-success col-sm-10 col-xs-10" href="@Url.Action("Users","Field")">
            <i class="fas fa-users"></i> Users
        </a>

        <a class="col-md-5 catlog btn btn-info col-sm-10 col-xs-10" href="@Url.Action("Recovery","Field")">
            <i class="fas fa-users-cog"></i> Recovery
        </a>

    </div>

</div>

LMS/Views/Field/Instructors.cshtml
@{
    ViewBag.Title = "Instructors";
}

<h2>Instructors</h2>

LMS/Views/Field/NewOrganization.cshtml
@{
    ViewBag.Title = "Add New Organization";
}

<div class="LMS_Header">
    <a href="@Url.Action("RoleAssignment","Field")" class="btn"><i class="fas fa-backward"></i> Back</a>
    <i class="fas fa-location-arrow"></i> @ViewBag.Title
</div>
<div class="LMS_body col-md-12 col-sm-12 col-xs-12">

    <form action="" method="post">

        <div class="form-group">
            <label class="control-label">
                Organization Name:
            </label>
            <input type="text" name="organizationName" class="form-control max-width" placeholder="Enter Organization Name" value="" required />
        </div>

        <div class="form-group">
            <label class="control-label">
                Organization Description:
            </label>
            <input type="text" name="organizationName" class="form-control max-width" placeholder="Enter Organization Description" value="" />
        </div>

        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label">
                        Organization Phone:
                    </label>
                    <input type="text" name="organizationName" class="form-control max-width" placeholder="Enter Organization Phone Number" value="" required />
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label">
                        Organization Tel:
                    </label>
                    <input type="text" name="organizationName" class="form-control max-width" placeholder="Enter Organization Tel Number" value="" />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label">
                        Email:
                    </label>
                    <input type="email" name="organizationName" class="form-control max-width" placeholder="Enter Organization Email Address" value="" required />
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label">
                        Website:
                    </label>
                    <input type="url" name="organizationName" class="form-control max-width" placeholder="Enter Organization Website URL" value="" required />
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label">
                Organization Address:
            </label>
            <input type="text" name="organizationName" class="form-control max-width" placeholder="Enter Organization Address" value="" required />
        </div>

        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label">
                        City:
                    </label>
                    <input type="text" name="organizationName" class="form-control max-width" placeholder="Enter Organization City" value="" />
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label">
                        Postal:
                    </label>
                    <input type="text" name="organizationName" class="form-control max-width" placeholder="Enter Organization Postal Code" value="" />
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label">
                        Country:
                    </label>
                    <input type="text" name="organizationName" class="form-control max-width" placeholder="Enter Organization Country" value="" />
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <br />
                <div class="form-group">
                    <a onclick="Cancel()" class="btn btn-warning"><i class="fas fa-ban"></i> Cancel</a>
                    <a onclick="AddOrganization()" class="btn btn-success"><i class="fas fa-location-arrow"></i> Add New Location</a>
                </div>
            </div>
        </div>

    </form>

</div>
<script>
    function AddOrganization() {
        debugger;
        swal({
            title: "Good job!",
            text: "You Have Added a New Organization in Portal!",
            icon: "success",
            button: "Go Back!",
        });
        setTimeout("location.href = '@Url.Action("RoleAssignment", "Field")';", 2000);
    }
        function Cancel() {
        debugger;
            swal("Oops", "The Record you have entered is not saved!", "error");
        setTimeout("location.href = '@Url.Action("RoleAssignment", "Field")';", 2000);
    }
</script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

LMS/Views/Field/NewUser.cshtml
@{
    ViewBag.Title = "New User";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<link rel="stylesheet" href="/path/to/cdn/bootstrap.min.css" />
<script src="/path/to/cdn/jquery.min.js"></script>
<script src="/path/to/cdn/bootstrap.min.js"></script>

<link rel="stylesheet" href="css/bootstrap-multiselect.css" type="text/css">
<script type="text/javascript" src="js/bootstrap-multiselect.js"></script>

<div class="LMS_Header">
    <a href="@Url.Action("Users","Field")" class="btn"><i class="fas fa-backward"></i> Back</a>
    <i class="fas fa-user-plus"></i> @ViewBag.Title
</div>
<div class="LMS_body">
    <form action="" method="post">
        <div class="form-group">
            <label class="control-label">
                Username
            </label>
            <input type="text" class="form-control max-width" placeholder="Enter UserName" name="name" value="" />
        </div>
        <div class="form-group">
            <label class="control-label">
                Email
            </label>
            <input type="email" class="form-control max-width" placeholder="Enter Email" name="name" value="" />
        </div>
        <div class="form-group">
            <label class="control-label">
                Role
            </label>
            <select class="form-control max-width">
                <option value="">Select Role</option>
                <option value="">IT</option>
                <option value="">Instructor</option>
                <option value="">Finance</option>
                <option value="">Student</option>
            </select>
        </div>
        <div class="form-group">
            <label class="control-label">Select Class</label>
            <select data-placeholder="Select Class to Assign User By There Role" multiple class="chosen-select max-width form-control" name="test">
                <option value="">Select Class to Assign User By There Role</option>
                <option value="">One</option>
                <option value="">Two</option>
                <option value="">Three</option>
            </select>
        </div>
        <div class="form-group">
            <label class="control-label">
                Status
            </label>
            <select class="form-control max-width" data-placeholder="Select Status">
                <option value="1">Active</option>
                <option value="0">DeActive</option>
            </select>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.jquery.js"></script>
        <link href="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.min.css" rel="stylesheet" />


        </form>
</div>


<script>

    $(".chosen-select").chosen({
        no_results_text: "Oops, nothing found!"
    });

</script>

LMS/Views/Field/Recovery.cshtml
@{
    ViewBag.Title = "Recovery";
}

<h2>Recovery</h2>

LMS/Views/Field/RoleAssignment.cshtml
@{
    ViewBag.Title = "Role Assignment";
}

<style>
    .catlog {
        padding: 1%;
        margin-top: 1%;
        margin-left: 6%;
        font-size: 20px;
        padding-top: 2%;
        padding-bottom: 2%;
    }

    .Assessment {
        background-color: red;
    }
</style>

<div class="LMS_Header">
    <a href="@Url.Action("Index","Field")" class="btn"><i class="fas fa-backward"></i> Back</a>

    <i class="fas fa-user-tag"></i> @ViewBag.Title
</div>
<div class="LMS_body col-sm-12 col-xs-12">

    <div class="row">

        <a class="col-md-5 catlog btn btn-warning col-sm-10 col-xs-10" href="@Url.Action("NewOrganization","Field")">
            <i class="fas fa-location-arrow"></i> Add New Organization
        </a>

        <a class="col-md-5 catlog btn btn-danger col-sm-10 col-xs-10" href="@Url.Action("ManageOrganization","Field")">
            <i class="fas fa-sitemap"></i> Update Organization
        </a>

        <a class="col-md-5 catlog btn btn-info col-sm-10 col-xs-10" href="@Url.Action("WebNewUser","Field")">
            <i class="fas fa-user-plus"></i> Add New User
        </a>

        <a class="col-md-5 catlog btn btn-primary col-sm-10 col-xs-10" href="@Url.Action("WebUsers","Field")">
            <i class="fas fa-users-cog"></i> Update User
        </a>

    </div>
</div>

LMS/Views/Field/Student.cshtml
@{
    ViewBag.Title = "Student";
}

<h2>Student</h2>

LMS/Views/Field/UserUpdate.cshtml
@{
    ViewBag.Title = "UserUpdate";
}

<h2>UserUpdate</h2>

LMS/Views/Field/Users.cshtml
@{
    ViewBag.Title = "Users";
}
<style>
    html {
        overflow: hidden;
    }

    ::-webkit-scrollbar {
        width: 12px;
    }

    ::-webkit-scrollbar-track {
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
        border-radius: 10px;
    }

    ::-webkit-scrollbar-thumb {
        border-radius: 10px;
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        background-color: #39903947;
        margin-right: 100px;
    }
</style>
<div class="LMS_Header">
    <div class="row">
        <div class="col-md-6 col-md-6 col-sm-12 col-xs-12">
            <a href="@Url.Action("Index","Field")" class="btn"><i class="fas fa-backward"></i> Back</a>
            <i class="fas fa-users"></i> @ViewBag.Title
        </div>

        <a href="@Url.Action("NewUser","Field")" class="col-md-4 col-md-4 col-sm-12 col-xs-12 btn btn-primary" style="margin-left:15%; color:white!important;"><i class="fas fa-user-plus"></i> Add New User </a>
    </div>
</div>
<div class="LMS_body col-sm-12 col-xs-12">

    <table class="table table-bordered table-striped table-hover table-responsive">
        <thead>
            <tr>
                <th class="col-lg-1 col-md-1">UserID</th>
                <th>Full Name</th>
                <th>Email</th>
                <th class="col-lg-1 col-md-1">Class</th>
                <th class="col-lg-1 col-md-1">Role</th>
                <th class="col-lg-1 col-md-1">Status</th>
                <th class="col-lg-1 col-md-1"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>

                <td>Syed Talha</td>
                <td>syed_talha@mobilelinkusa.com</td>
                <td>One</td>
                <td>Student</td>
                <td><button class="btn alert-success"> <i class="fas fa-unlock-alt"></i> Active </button></td>
                <td><a class="btn btn-warning" href="@Url.Action("UserUpdate")"><i class="fas fa-edit"></i> Update</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Syed Talha</td>
                <td>syed_talha@mobilelinkusa.com</td>
                <td>Two</td>
                <td>Student</td>
                <td><button class="btn alert-danger"><i class="fas fa-user-lock"></i> Locked </button></td>
                <td><a class="btn btn-warning" href="@Url.Action("UserUpdate")"><i class="fas fa-edit"></i> Update</a></td>
            </tr>
            <tr>
                <td>3</td>
                <td>Suleman</td>
                <td>muhammad_suleman@mobilelinkusa.com</td>
                <td>- - -</td>
                <td>Instructor</td>
                <td><button class="btn alert-success"><i class="fas fa-unlock-alt"></i> Active </button></td>
                <td><a class="btn btn-warning" href="@Url.Action("UserUpdate")"><i class="fas fa-edit"></i> Update</a></td>
            </tr>
        </tbody>
    </table>

</div>

<script>
    window.console.log("hello world");
    console.log("hello world");
</script>

LMS/Views/Field/WebNewUser.cshtml
@{
    ViewBag.Title = "WebNewUser";
}

<h2>WebNewUser</h2>

LMS/Views/Field/WebUpdateUser.cshtml
@{
    ViewBag.Title = "WebUpdateUser";
}

<h2>WebUpdateUser</h2>

LMS/Views/Field/WebUsers.cshtml
@{
    ViewBag.Title = "WebUsers";
}

<h2>WebUsers</h2>